import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/features/common/Header/components/index";
import { Suspense } from "react";
import Loading from "./loading";
import { createClient } from "@/lib/supabase/client/serverClient";
import { UserType } from "@/types/user";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const { data } = await supabase.auth.getUser();
  const auth = data?.user;
  let user: UserType | null = null;
  if (auth) {
    const { data: profile, error: profileError } = await supabase
      .from("users")
      .select("*")
      .eq("id", auth.id)
      .single();

    if (profileError) {
      console.error("ユーザープロファイルの取得エラー:", profileError.message);
      // 必要に応じてエラーハンドリングを追加
    } else {
      user = profile;
    }
  }
  console.log(user);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loading />}>
          <Header user={user} />
          {children}
        </Suspense>
        <footer className="bg-purple-800 text-white p-4 mt-8">
          <div className="container mx-auto text-center">
            <p> © 2024 TATSULOG. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
